FinalProject.UI.MVC/Controllers/CoursesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FinalProject.DATA.EF;

namespace FinalProject.UI.MVC.Controllers
{
    
    public class CoursesController : Controller
    {
        private LMSEntities db = new LMSEntities();


        [Authorize(Roles = "Admin, Employee, Manager")]
        // GET: Courses
        public ActionResult Index()
        {
            return View(db.Courses.ToList());
        }

        [Authorize(Roles = "Admin, Employee, Manager")]
        // GET: Courses/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Course course = db.Courses.Find(id);
            if (course == null)
            {
                return HttpNotFound();
            }
            return View(course);
        }

        [Authorize (Roles = "Admin")]
        // GET: Courses/Create
        public ActionResult Create()
        {
            return View();
        }


        [Authorize(Roles = "Admin")]
        // POST: Courses/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CourseId,CourseName,CourseDescription,IsActive")] Course course)
        {
            if (ModelState.IsValid)
            {
                db.Courses.Add(course);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(course);
        }

        [Authorize(Roles = "Admin")]
        // GET: Courses/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Course course = db.Courses.Find(id);
            if (course == null)
            {
                return HttpNotFound();
            }
            return View(course);
        }

        [Authorize(Roles = "Admin")]
        // POST: Courses/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CourseId,CourseName,CourseDescription,IsActive")] Course course)
        {
            if (ModelState.IsValid)
            {
                db.Entry(course).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(course);
        }


        [Authorize(Roles = "Admin")]
        // GET: Courses/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Course course = db.Courses.Find(id);
            if (course == null)
            {
                return HttpNotFound();
            }
            return View(course);
        }


        [Authorize(Roles = "Admin")]
        // POST: Courses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Course course = db.Courses.Find(id);
            db.Courses.Remove(course);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FinalProject.UI.MVC/Controllers/LessonsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using FinalProject.DATA.EF;
using Microsoft.AspNet.Identity;

namespace FinalProject.UI.MVC.Controllers
{
    public class LessonsController : Controller
    {
        private LMSEntities db = new LMSEntities();

        // GET: Lessons
        public ActionResult Index()
        {
            var lessons = db.Lessons.Include(l => l.Cours);
            return View(lessons.ToList());
        }

        [Authorize(Roles = "Admin, Employee, Manager")]
        // GET: Lessons/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Lesson lesson = db.Lessons.Find(id);
            if (lesson == null)
            {
                return HttpNotFound();
            }

            if (User.IsInRole("Employee"))
            {
                LessonView lv = new LessonView();
                lv.UserId = User.Identity.GetUserId();
                lv.DateViewed = DateTime.Now;
                lv.LessonId = id;

                LessonView lvDupe = db.LessonViews.Where(x => x.LessonId == id && x.UserId == lv.UserId).SingleOrDefault();
                if (lvDupe == null)
                {
                    db.LessonViews.Add(lv);
                    db.SaveChanges();
                }


                int nbrLessons = db.Lessons.Where(x => x.CourseId == lesson.CourseId).Count();
                string userid = User.Identity.GetUserId();

                int nbrLessonViews = db.LessonViews.Where(x => x.Lesson.CourseId == lesson.CourseId && x.UserId == userid).Count();

                
                if (nbrLessons == nbrLessonViews)
                {
                   
                    CourseCompletion cc = new CourseCompletion();
                    cc.UserId = User.Identity.GetUserId();
                    cc.DateCompleted = DateTime.Now;
                    cc.CourseId = lesson.CourseId;

                    db.CourseCompletions.Add(cc);
                    db.SaveChanges();

                    var currentUserDetails = db.UserDetails.Where(x => x.UserId == cc.UserId).SingleOrDefault(); 

                    

                        
              
                    string messageBody2 = $" {currentUserDetails.FirstName} {currentUserDetails.LastName} has completed the following course: {lesson.Cours.CourseName} on {cc.DateCompleted}.";

                    MailMessage m = new MailMessage("noreply@kccodes.com", "kristin.cartmill@outlook.com", "Message From Edgewater Medical Center LMS", messageBody2);

                    m.IsBodyHtml = true;

                    SmtpClient mailServer = new SmtpClient("mail.kccodes.com");
                    mailServer.Credentials = new NetworkCredential("noreply@kccodes.com", "Puppies#1");

                    try
                    {
                        //attempt to send the email
                        mailServer.Send(m);
                    }
                    catch (System.Exception ex)
                    {
                        ////if they land here, sending email failed
                        //ViewBag.CustomerMessage =
                        //    $"We're sorry, the request failed. Please try again later.<h2>Error</h2>{ex.StackTrace}";
                        //return View();
                    }
                }
            }

            if (lesson.VideoURL !=null){


                var v = lesson.VideoURL.IndexOf("v=");
                var amp = lesson.VideoURL.IndexOf("&", v);
                string vid;
                // if the video id is the last value in the url
                if (amp == -1)
                {
                    vid = lesson.VideoURL.Substring(v + 2);
                    // if there are other parameters after the video id in the url
                }
                else
                {
                    vid = lesson.VideoURL.Substring(v + 2, amp - (v + 2));
                }
                ViewBag.VideoID = vid;

            }


            return View(lesson);
        }

        [Authorize(Roles = "Admin")]
        // GET: Lessons/Create
        public ActionResult Create()
        {
            ViewBag.CourseId = new SelectList(db.Courses, "CourseId", "CourseName");
            return View();
        }

        [Authorize(Roles = "Admin")]
        // POST: Lessons/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "LessonId,LessonTitle,CourseId,Introduction,VideoURL,PdfFilename,IsActive")] Lesson lesson, HttpPostedFileBase lessonPdf)
        {
            if (ModelState.IsValid)
            {

                
                string pdfName = "NoDocument.pdf";//default name if none uploaded

                if (lessonPdf != null)
                {
                    pdfName = lessonPdf.FileName;
                    //this code is alternative to using the substring to get the extension
                    //the substring code will operate here as well.
                    //file was uploaded - process it.
                    string ext = pdfName.Substring(pdfName.LastIndexOf('.'));

                    //create a list of good extensions
                    string[] allowedExtentions = { ".pdf" };

                    if (allowedExtentions.Contains(ext.ToLower()))
                    {
                        //we can save the image name under numerous approaches,
                        //but the most important thing is that its unique
                        //quickest way = GUID
                        lessonPdf.SaveAs(Server.MapPath("/Content/images/PDFs/" + pdfName));

                    }

                    else
                    {
                        pdfName = "NoDocument.pdf";

                    }
                }
                lesson.PdfFilename = pdfName;


                db.Lessons.Add(lesson);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CourseId = new SelectList(db.Courses, "CourseId", "CourseName", lesson.CourseId);
            return View(lesson);
        }

        [Authorize(Roles = "Admin")]
        // GET: Lessons/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Lesson lesson = db.Lessons.Find(id);
            if (lesson == null)
            {
                return HttpNotFound();
            }
            ViewBag.CourseId = new SelectList(db.Courses, "CourseId", "CourseName", lesson.CourseId);
            return View(lesson);
        }

        [Authorize(Roles = "Admin")]
        // POST: Lessons/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "LessonId,LessonTitle,CourseId,Introduction,VideoURL,PdfFilename,IsActive")] Lesson lesson, HttpPostedFileBase lessonPdf)
        {
            if (ModelState.IsValid)
            {
                if (lessonPdf != null)
                {
                    string pdfName = lessonPdf.FileName;

                    string ext = pdfName.Substring(pdfName.LastIndexOf('.'));

                    //create a list of good extensions
                    string[] allowedExtentions = { ".pdf" };

                    if (allowedExtentions.Contains(ext.ToLower()))
                    {

                        lessonPdf.SaveAs(Server.MapPath("/Content/images/PDFs/" + pdfName));

                        lesson.PdfFilename = pdfName;
                    }

                    //else
                    //{
                    //    pdfName = "NoDocument.pdf";
                    //}                   

                }

                
                db.Entry(lesson).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("CourseLessons", new { id = lesson.CourseId});
            }
        
            ViewBag.CourseId = new SelectList(db.Courses, "CourseId", "CourseName", lesson.CourseId);
            return View(lesson);
        }




        [Authorize(Roles = "Admin")]
        // GET: Lessons/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Lesson lesson = db.Lessons.Find(id);
            if (lesson == null)
            {
                return HttpNotFound();
            }
            return View(lesson);
        }

        [Authorize(Roles = "Admin")]
        // POST: Lessons/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Lesson lesson = db.Lessons.Find(id);
            db.Lessons.Remove(lesson);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult CourseLessons(int id)
        {
            var lessons = db.Lessons.Where(x => x.CourseId == id);

FinalProject.UI.MVC/Views/Shared/_Layout.cshtml
<!doctype html>
<html lang="en">
<head>
    <title>Edgewater Medical Center</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="~/Content/images/favicon.ico" rel="icon">
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,900" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Chilanka|Coming+Soon|Pangolin|Special+Elite&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Work+Sans&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Mada&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="~/Content/css/bootstrap.css">
    <link rel="stylesheet" href="~/Content/css/animate.css">
    <link rel="stylesheet" href="~/Content/css/owl.carousel.min.css">
    <link rel="stylesheet" href="~/Content/fonts/ionicons/css/ionicons.min.css">
    <link rel="stylesheet" href="~/Content/fonts/fontawesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/Content/fonts/flaticon/font/flaticon.css">
    <!-- Theme Style -->
    <link rel="stylesheet" href="~/Content/css/style.css">

    <link href="https://fonts.googleapis.com/css?family=Inconsolata" rel="stylesheet">


    @Styles.Render("~/Content/css")
    @RenderSection("htmlHead", required: false)
</head>
<body>
    <header role="banner">
        <nav class="navbar navbar-expand-md navbar-dark bg-light">
            <div class="container">
                <a class="navbar-brand absolute" href="@Url.Action("Index", "Home")">Edgewater Medical Center</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample05" aria-controls="navbarsExample05" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse navbar-light" id="navbarsExample05">
                    <ul class="navbar-nav mx-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("Index", "Home")"></a>
                        </li>
                        @if (Request.IsAuthenticated && User.IsInRole("Employee") | User.IsInRole("Manager") | User.IsInRole("Admin"))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="@Url.Action("Index", "Courses")" id="dropdown04" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Courses</a>
                                <div class="dropdown-menu" aria-labelledby="dropdown04">
                                    <a class="dropdown-item" href="@Url.Action("Index", "Courses")">All Courses</a>
                                    <a class="dropdown-item" href="@Url.Action("CourseLessons", "Lessons", new { id = "220" })">Medication Safety &amp; Administration</a>
                                    <a class="dropdown-item" href="@Url.Action("CourseLessons", "Lessons", new { id = "180" })">Patient Safety</a>
                                    <a class="dropdown-item" href="@Url.Action("CourseLessons", "Lessons", new { id = "790" })">Cardiac</a>
                                    <a class="dropdown-item" href="@Url.Action("CourseLessons", "Lessons", new { id = "802" })">Psych</a>
                                    <a class="dropdown-item" href="@Url.Action("CourseLessons", "Lessons", new { id = "880" })">Critical Care</a>
                                    <a class="dropdown-item" href="@Url.Action("CourseLessons", "Lessons", new { id = "990" })">Neuro</a>
                                </div>
                            </li>
                        }

                        @if (Request.IsAuthenticated && User.IsInRole("Employee") | User.IsInRole("Manager"))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="dropdown05" data-toggle="dropdown" aria-haspopup="true"
                                   aria-expanded="false" style="padding-left:10px">Learning Profile</a>
                                <div class="dropdown-menu" aria-labelledby="dropdown05">
                                    <a class="dropdown-item" href="@Url.Action("Index", "CourseCompletions")">Completed Courses</a>
                                    <a class="dropdown-item" href="@Url.Action("Index", "LessonViews")">Lessons Completed</a>
                                </div>
                            </li>
                        }
                        @if (Request.IsAuthenticated && User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link" href="@Url.Action("Index", "Lessons")">Lessons</a>
                            </li>
                        }

                        @if (Request.IsAuthenticated && User.IsInRole("Admin"))
                        {
                            @*<li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="dropdown05" data-toggle="dropdown" aria-haspopup="true"
               aria-expanded="false">Admin</a>
            <div class="dropdown-menu" aria-labelledby="dropdown05">*@
                            <li class="nav-item dropdown" style="padding-left:10px">
                                <a class="nav-link dropdown-toggle" href="#" id="dropdown06" data-toggle="dropdown" aria-haspopup="true"
                                   aria-expanded="false">Admin</a>
                                <div class="dropdown-menu" aria-labelledby="dropdown06">
                                    <a class="dropdown-item" href="@Url.Action("Index", "RolesAdmin")">Role Admin</a>
                                    <a class="dropdown-item" href="@Url.Action("Index", "UsersAdmin")">User Admin</a>
                                </div>
                            </li>
                        }
                    </ul>
                    <ul class="navbar-nav absolute-right">
                        <li class="nav-item login-partial">
                            @Html.Partial("_LoginPartial", new { @class = "nav-link" })
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <section class="site-hero site-hero-innerpage overlay" data-stellar-background-ratio="0.5" style="background-image: url(/Content/images/HeaderBackground2.jpg);">
        <div class="container">
            <div class="row align-items-center site-hero-inner justify-content-center">
                <div class="col-md-8 text-center">
                    <div class="mb-5 element-animate">
                        <h1>@ViewBag.Title</h1>
                        @RenderSection("html", required: false)
                    </div>
                </div>
            </div>
        </div>
    </section>
    @RenderBody()

    <footer class="site-footer" style="background-image: url(/Content/images/imageedit_3_9838745579[35].jpg);">
        <div class="container">
            <div class="row mb-5">
                <div class="col-md-4">
                    <h3>About</h3>
                    <p>Edgewater Medical Center is a leader in providing patients with compassionate, state-of-the-art care, offering a range of general and specialized medical and nursing services. We have over 1,000 physicians, surgeons and nurses at our main medical center and ambulatory care centers throughout the Chicago area. Our knowledge of innovative treatments is enhanced by our dedication to maintaining the highest standard of care.</p>
                </div>
                <div class="col-md-6 ml-auto">
                    <div class="row">
                        <div class="col-md-4">
                            <ul class="list-unstyled">
                                <li>  <a class="nav-link" href="@Url.Action("Index", "Home")"></a></li>
                                <li>  <a class="nav-link" href="@Url.Action("Index", "Courses")">Courses</a></li>
                                <li>  <a class="nav-link" href="@Url.Action("Register", "Account")">Register</a></li>
                                <li>  <a class="nav-link" href="@Url.Action("Login", "Account")">Log In</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <p>
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        Copyright &copy;
                        <script>document.write(new Date().getFullYear());</script> All rights reserved | Kristin Cartmill | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    </p>
                </div>
            </div>
        </div>
    </footer>
    <!-- END footer -->
    <!-- loader -->
    <div id="loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee" /><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#f4b214" /></svg></div>
    <script src="~/Content/js/jquery-3.2.1.min.js"></script>
    <script src="~/Content/js/jquery-migrate-3.0.0.js"></script>
    <script src="~/Content/js/popper.min.js"></script>
    <script src="~/Content/js/bootstrap.min.js"></script>
    <script src="~/Content/js/owl.carousel.min.js"></script>
    <script src="~/Content/js/jquery.waypoints.min.js"></script>
    <script src="~/Content/js/jquery.stellar.min.js"></script>

    <script src="~/Content/js/main.js"></script>
    @RenderSection("Scripts", false)
</body>
</html>

FinalProject.UI.MVC/Views/Shared/_OrigLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("About", "About")</li>

                    @if (Request.IsAuthenticated && User.IsInRole("Admin")) {
                        <li>@Html.ActionLink("RolesAdmin", "Index", "RolesAdmin")</li>
                        <li>@Html.ActionLink("UsersAdmin", "Index", "UsersAdmin")</li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>